package com.desafio.labs.exception

class ExceptionResponse( val code : String, val message : String ) {
}